"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from distutils.core import setup
import py2app
import frigo

APP = ['scripts/frigoReplicator.py']
OPTIONS = {'argv_emulation': True,
           'iconfile': 'icon.icns' # icon files shall be 'icns' type
} 

setup(
    app=APP,
    name = "frigo",
    version = frigo.__version__, 
    author = "Society for Arts and Technologies",
    author_email = "metalab@sat.qc.ca",
    url = "http://code.sat.qc.ca/",
    description = "Digital Assets Replicator",
    long_description = """Digital Assets Replicator""",
    install_requires = [], # "twisted", "wxpython", "docutils", "unison"
    license = "GPL",
    platforms = ["any"],
    zip_safe = True,
    packages = ["frigo", "frigo/web", "frigo/web/data", "frigo/web/data/images"],
    package_data = {
        "":["*.cfg", "*.png", "*.jpg", "*.json", "*.txt", "*.rst"]
    },
    #package_dir = {'': 'frigo','':'frigo/web'},
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],  
)

